name: Restrict Commits to Folder

on:
  push:
    paths:
      - "restricted-folder/**"

jobs:
  restrict-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit author
      run: |
        COMMIT_AUTHOR=$(git log -1 --pretty=format:'%ae')
        RESTRICTED_USER="shudhanshu.raj@amoga.io"

        if [ "$COMMIT_AUTHOR" = "$RESTRICTED_USER" ]; then
          echo "User $COMMIT_AUTHOR is not allowed to commit to this folder."
          exit 1
        fi
