 name: Restrict folder commits

on:
  push:
    branches:
      - main
      - 'module-*' 

jobs:
  restrict-folder-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Ensure we fetch the last two commits

    - name: Restrict commits to specific folder
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q '^restricted-folder/'; then
          echo "You are not allowed to commit to the 'restricted-folder/' directory."
          exit 1
        fi
      shell: /usr/bin/bash -e {0}
