name: Restrict Commits to Folder

on:
  push:
    paths:
      - "core/**"

jobs:
  restrict-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit author
      run: |
        echo "I am here"
         COMMIT_AUTHOR="shudhanshu.raj@amoga.io"
        RESTRICTED_USER="restricted_user@example.com"

        if [ "$COMMIT_AUTHOR" = "shudhanshu.raj@amoga.io" ]; then
          echo "User $COMMIT_AUTHOR is not allowed to commit to this folder."
          exit 1
        fi
