name: Restrict folder commits

on:
  push:
    branches:
      - main
      - 'module-*'

jobs:
  restrict-folder-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Restrict commits to specific folder
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q '^core/'; then
          echo "You are not allowed to commit to the 'core/' directory."
          exit 1
        fi
